platform :ios, '9.0'
use_frameworks!

target 'HealthKitReporter_Example' do
  pod 'HealthKitReporter', :path => '../', :testspecs => ['Tests']
end

target 'HealthKitReporter_Tests' do
  inherit! :search_paths
end
 
